//! Windows backend — the meticulous one.
//!
//! * Elevation: `GetTokenInformation(TokenElevation)`; without admin, `flash`
//!   fails with a hint and the UI offers "Restart as admin" (PowerShell
//!   `Start-Process -Verb RunAs` with the `--elevated` flag).
//! * Enumeration: drive letters → volume handles →
//!   `IOCTL_STORAGE_GET_DEVICE_NUMBER` → PhysicalDrive number; disk metadata
//!   via `IOCTL_STORAGE_QUERY_PROPERTY` (vendor/product/serial/removable/bus)
//!   and `IOCTL_DISK_GET_LENGTH_INFO` for the size.
//! * Writing: `\\.\PhysicalDrive{n}` opened with
//!   `FILE_FLAG_NO_BUFFERING` → buffers and lengths are ALIGNED to the
//!   sector reported by `IOCTL_DISK_GET_DRIVE_GEOMETRY` (fallback 512).
//!   Every volume of the disk is locked + dismounted before the first write.
//! * Ejection: `IOCTL_STORAGE_EJECT_MEDIA` on the PhysicalDrive handle.
//!
//! Implementation note: small Win32 output structs (STORAGE_DEVICE_NUMBER,
//! GET_LENGTH_INFORMATION, DISK_GEOMETRY, STORAGE_DEVICE_DESCRIPTOR) are
//! parsed manually from byte buffers. This avoids depending on the exact
//! struct definitions generated by windows-rs and keeps every field access
//! bounds-checked.

use std::alloc::Layout;
use std::io;
use std::path::Path;
use std::process::Command;

use windows::core::{HSTRING, PCWSTR};
use windows::Win32::Foundation::{CloseHandle, HANDLE};
use windows::Win32::Security::{
    GetTokenInformation, OpenProcessToken, TokenElevation, TOKEN_ELEVATION, TOKEN_QUERY,
};
use windows::Win32::Storage::FileSystem::{
    CreateFileW, FILE_FLAG_NO_BUFFERING, FILE_SHARE_READ, FILE_SHARE_WRITE, FSCTL_DISMOUNT_VOLUME,
    FSCTL_LOCK_VOLUME, GENERIC_READ, GENERIC_WRITE, IOCTL_STORAGE_EJECT_MEDIA,
    IOCTL_STORAGE_GET_DEVICE_NUMBER, OPEN_EXISTING,
};
use windows::Win32::Storage::IOCTL_STORAGE_QUERY_PROPERTY;
use windows::Win32::System::Ioctl::{IOCTL_DISK_GET_DRIVE_GEOMETRY, IOCTL_DISK_GET_LENGTH_INFO};
use windows::Win32::System::Threading::GetCurrentProcess;
use windows::Win32::System::IO::DeviceIoControl;

use crate::core::writer::{BlockReader, BlockWriter};
use crate::core::EventSink;
use crate::error::AppError;
use crate::safety::DriveInfo;

// ---------------------------------------------------------------------------
// Small helpers
// ---------------------------------------------------------------------------

fn werr(e: windows::core::Error) -> AppError {
    AppError::Device {
        message: format!("Win32 error: {e}"),
        hint: Some("Close any window or program using the drive and try again.".to_string()),
    }
}

fn io_err(e: io::Error) -> AppError {
    AppError::Device {
        message: format!("device I/O error: {e}"),
        hint: Some(crate::safety::HINT_UNKNOWN_STATE.to_string()),
    }
}

/// Open a Win32 path (volume or PhysicalDrive) with the given access.
fn open_path(path: &str, read: bool, write: bool, no_buffering: bool) -> Result<HANDLE, AppError> {
    let wide = HSTRING::from(path);
    let mut access = 0u32;
    if read {
        access |= GENERIC_READ.0;
    }
    if write {
        access |= GENERIC_WRITE.0;
    }
    let flags = if no_buffering {
        FILE_FLAG_NO_BUFFERING
    } else {
        Default::default()
    };
    unsafe {
        CreateFileW(
            PCWSTR(wide.as_ptr()),
            access,
            FILE_SHARE_READ | FILE_SHARE_WRITE,
            None,
            OPEN_EXISTING,
            flags,
            None,
        )
        .map_err(werr)
    }
}

/// DeviceIoControl with manual buffers (bounded, bounds-checked parsing).
fn ioctl(
    handle: HANDLE,
    code: u32,
    input: Option<(*const u8, u32)>,
    output: Option<(*mut u8, u32)>,
) -> Result<(), AppError> {
    let mut returned = 0u32;
    let (in_ptr, in_len) = match input {
        Some((p, l)) => (Some(p.cast()), l),
        None => (None, 0),
    };
    let (out_ptr, out_len) = match output {
        Some((p, l)) => (Some(p.cast()), l),
        None => (None, 0),
    };
    unsafe {
        DeviceIoControl(
            handle,
            code,
            in_ptr,
            in_len,
            out_ptr,
            out_len,
            Some(&mut returned),
            None,
        )
    }
    .map_err(werr)
}

fn u32_at(buf: &[u8], offset: usize) -> Option<u32> {
    if offset + 4 <= buf.len() {
        Some(u32::from_le_bytes([
            buf[offset],
            buf[offset + 1],
            buf[offset + 2],
            buf[offset + 3],
        ]))
    } else {
        None
    }
}

fn cstr_at(buf: &[u8], offset: u32) -> String {
    let start = offset as usize;
    if start == 0 || start >= buf.len() {
        return String::new();
    }
    let end = buf[start..]
        .iter()
        .position(|&c| c == 0)
        .map(|p| start + p)
        .unwrap_or(buf.len());
    String::from_utf8_lossy(&buf[start..end]).trim().to_string()
}

// ---------------------------------------------------------------------------
// Elevation
// ---------------------------------------------------------------------------

/// True when the current process token is elevated (runs as admin).
pub fn is_elevated() -> bool {
    unsafe {
        let mut token = HANDLE::default();
        if OpenProcessToken(GetCurrentProcess(), TOKEN_QUERY, &mut token).is_err() {
            return false;
        }
        let mut elevation = TOKEN_ELEVATION::default();
        let mut returned = 0u32;
        let ok = GetTokenInformation(
            token,
            TokenElevation,
            Some(&mut elevation as *mut TOKEN_ELEVATION as *mut _),
            std::mem::size_of::<TOKEN_ELEVATION>() as u32,
            &mut returned,
        )
        .is_ok();
        let _ = CloseHandle(token);
        ok && elevation.TokenIsElevated != 0
    }
}

/// Relaunch AnimaBooter with the `runas` verb (PowerShell), then exit.
pub fn restart_as_admin() -> Result<(), AppError> {
    let exe = std::env::current_exe()
        .map_err(|e| AppError::platform(format!("cannot locate current executable: {e}")))?;
    let exe_str = exe.to_string_lossy().replace('\'', "");
    let script =
        format!("Start-Process -FilePath '{exe_str}' -Verb RunAs -ArgumentList '--elevated'");
    let spawned = Command::new("powershell")
        .args(["-NoProfile", "-WindowStyle", "Hidden", "-Command", &script])
        .spawn();
    match spawned {
        Ok(_) => {
            // Parent hands control over to the elevated instance.
            std::process::exit(0);
        }
        Err(e) => Err(AppError::Platform {
            message: format!("could not launch elevated restart: {e}"),
            hint: Some(
                "Right-click the app and choose 'Run as administrator' manually.".to_string(),
            ),
        }),
    }
}

// ---------------------------------------------------------------------------
// Enumeration
// ---------------------------------------------------------------------------

/// Map a drive letter to its PhysicalDrive number via
/// IOCTL_STORAGE_GET_DEVICE_NUMBER. Returns (device_number, partition).
fn volume_device_number(letter: char) -> Option<(u32, u32)> {
    let path = format!(r"\\.\{letter}:");
    let handle = open_path(&path, true, false, false).ok()?;
    // STORAGE_DEVICE_NUMBER { DeviceType: u32, DeviceNumber: u32, PartitionNumber: u32 }
    let mut out = [0u8; 12];
    let result = ioctl(
        handle,
        IOCTL_STORAGE_GET_DEVICE_NUMBER,
        None,
        Some((out.as_mut_ptr(), out.len() as u32)),
    );
    let _ = unsafe { CloseHandle(handle) };
    result.ok()?;
    let device_number = u32_at(&out, 4).unwrap_or(u32::MAX);
    let partition = u32_at(&out, 8).unwrap_or(0);
    Some((device_number, partition))
}

/// (vendor, product, serial, bus_type_byte, removable, size_bytes)
type DriveProperties = (String, String, String, u8, bool, u64);

fn drive_properties(physical: u32) -> Option<DriveProperties> {
    let path = format!(r"\\.\PhysicalDrive{physical}");
    let handle = open_path(&path, true, false, false).ok()?;

    // Size: IOCTL_DISK_GET_LENGTH_INFO -> GET_LENGTH_INFORMATION { Length: i64 }
    let mut len_buf = [0u8; 16];
    let size = ioctl(
        handle,
        IOCTL_DISK_GET_LENGTH_INFO,
        None,
        Some((len_buf.as_mut_ptr(), 16)),
    )
    .ok()
    .and_then(|_| {
        let raw = i64::from_le_bytes(len_buf[0..8].try_into().ok()?);
        Some(raw.max(0) as u64)
    })
    .unwrap_or(0);

    // Geometry: DISK_GEOMETRY.BytesPerSector sits at offset 20
    // (LARGE_INTEGER Cylinders[8], MediaType[4], TracksPerCylinder[4], SectorsPerTrack[4]).
    let mut geo_buf = [0u8; 24];
    let _ = ioctl(
        handle,
        IOCTL_DISK_GET_DRIVE_GEOMETRY,
        None,
        Some((geo_buf.as_mut_ptr(), geo_buf.len() as u32)),
    );
    let _sector = u32_at(&geo_buf, 20).unwrap_or(512);

    // StorageDeviceProperty descriptor (variable length, 1 KiB is plenty).
    // The query buffer encodes STORAGE_PROPERTY_QUERY with zeroed fields:
    // PropertyId = 0 (StorageDeviceProperty), QueryType = 0 (StandardQuery).
    let mut query = [0u8; 8];
    let mut out = [0u8; 1024];
    let mut props: DriveProperties = (String::new(), String::new(), String::new(), 0, false, size);
    if ioctl(
        handle,
        IOCTL_STORAGE_QUERY_PROPERTY,
        Some((query.as_ptr(), query.len() as u32)),
        Some((out.as_mut_ptr(), out.len() as u32)),
    )
    .is_ok()
    {
        let removable = out.get(10).copied().unwrap_or(0) != 0; // BOOLEAN RemovableMedia
        let bus = out.get(28).copied().unwrap_or(0); // STORAGE_BUS_TYPE BusType
        let vendor = cstr_at(&out, u32_at(&out, 12).unwrap_or(0)); // VendorIdOffset
        let product = cstr_at(&out, u32_at(&out, 16).unwrap_or(0)); // ProductIdOffset
        let serial = cstr_at(&out, u32_at(&out, 24).unwrap_or(0)); // SerialNumberOffset
        props = (vendor, product, serial, bus, removable, size);
    }
    let _ = unsafe { CloseHandle(handle) };
    Some(props)
}

/// ProductIdOffset lives at byte 16 of STORAGE_DEVICE_DESCRIPTOR (kept as a
/// named helper for readability).
#[allow(dead_code)]
fn product_id_offset(buf: &[u8]) -> u32 {
    u32_at(buf, 16).unwrap_or(0)
}

fn is_system_drive(physical: u32) -> bool {
    let system_root = std::env::var("SystemRoot").unwrap_or_else(|_| "C:\\Windows".to_string());
    let Some(letter) = system_root.chars().next() else {
        return false;
    };
    matches!(volume_device_number(letter), Some((dev, _)) if dev == physical)
}

const BUS_TYPE_USB: u8 = 7;
const BUS_TYPE_SD: u8 = 12;
const BUS_TYPE_SATA: u8 = 11;
const BUS_TYPE_NVME: u8 = 17;

pub fn list_drives(unsafe_mode: bool) -> Result<Vec<DriveInfo>, AppError> {
    // Windows always assigns letters to mounted volumes; grouping them by
    // PhysicalDrive number covers every disk the user could target.
    let mask = unsafe { windows::Win32::Storage::FileSystem::GetLogicalDrives() };
    let mut physicals: Vec<u32> = Vec::new();
    for i in 0..26u32 {
        if mask & (1 << i) == 0 {
            continue;
        }
        let letter = (b'A' + i as u8) as char;
        if let Some((number, _)) = volume_device_number(letter) {
            if !physicals.contains(&number) {
                physicals.push(number);
            }
        }
    }
    physicals.sort_unstable();

    let mut drives = Vec::new();
    for physical in physicals {
        let Some((vendor, product, serial, bus, removable, size)) = drive_properties(physical)
        else {
            continue;
        };
        if !removable && !unsafe_mode {
            continue;
        }
        let bus_str = match bus {
            BUS_TYPE_USB => "usb",
            BUS_TYPE_SD => "sd",
            BUS_TYPE_SATA => "sata",
            BUS_TYPE_NVME => "nvme",
            _ => "other",
        }
        .to_string();
        drives.push(DriveInfo {
            id: format!("PhysicalDrive{physical}"),
            path: format!(r"\\.\PhysicalDrive{physical}"),
            model: if product.is_empty() {
                "USB Device".to_string()
            } else {
                product
            },
            vendor,
            size_bytes: size,
            removable,
            bus: bus_str,
            serial,
            is_system: is_system_drive(physical),
        });
    }
    Ok(drives)
}

// ---------------------------------------------------------------------------
// Aligned buffer (FILE_FLAG_NO_BUFFERING requires aligned address/length)
// ---------------------------------------------------------------------------

struct AlignedBuffer {
    ptr: *mut u8,
    layout: Layout,
    size: usize,
}

// The raw pointer is only ever accessed through &mut self methods.
unsafe impl Send for AlignedBuffer {}

impl AlignedBuffer {
    fn new(size: usize, align: usize) -> Option<Self> {
        let layout = Layout::from_size_align(size, align.max(8)).ok()?;
        let ptr = unsafe { std::alloc::alloc(layout) };
        if ptr.is_null() {
            return None;
        }
        Some(Self { ptr, layout, size })
    }

    fn slice_mut(&mut self) -> &mut [u8] {
        unsafe { std::slice::from_raw_parts_mut(self.ptr, self.size) }
    }
}

impl Drop for AlignedBuffer {
    fn drop(&mut self) {
        unsafe { std::alloc::dealloc(self.ptr, self.layout) };
    }
}

// ---------------------------------------------------------------------------
// Writer / reader handles
// ---------------------------------------------------------------------------

pub struct WindowsWriter {
    file: std::fs::File, // owns the HANDLE; closed on drop
    scratch: AlignedBuffer,
    sector: usize,
}

impl WindowsWriter {
    fn new(handle: HANDLE, sector: usize) -> Result<Self, AppError> {
        use std::os::windows::io::FromRawHandle;
        // SAFETY: ownership of `handle` moves into the File; CloseHandle is
        // never called on it again.
        let file =
            unsafe { std::fs::File::from_raw_handle(handle.0 as std::os::windows::io::RawHandle) };
        let scratch = AlignedBuffer::new(crate::core::BLOCK_SIZE + sector * 2, sector)
            .ok_or_else(|| AppError::device("cannot allocate aligned write buffer"))?;
        Ok(Self {
            file,
            scratch,
            sector,
        })
    }
}

impl BlockWriter for WindowsWriter {
    fn write_at(&mut self, offset: u64, data: &[u8]) -> io::Result<()> {
        use std::io::{Seek, Write};
        debug_assert_eq!(
            offset % self.sector as u64,
            0,
            "offset must be sector-aligned"
        );
        let aligned_len = data.len().div_ceil(self.sector) * self.sector;
        let scratch = &mut self.scratch;
        let slice = scratch.slice_mut();
        if aligned_len > slice.len() {
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                "block larger than aligned scratch buffer",
            ));
        }
        slice[..data.len()].copy_from_slice(data);
        slice[data.len()..aligned_len].fill(0); // pad the final partial sector
        self.file.seek(std::io::SeekFrom::Start(offset))?;
        self.file.write_all(&slice[..aligned_len])
    }

    fn sync(&mut self) -> io::Result<()> {
        self.file.sync_all()
    }

    fn sector_size(&self) -> u64 {
        self.sector as u64
    }
}

pub struct WindowsReader {
    file: std::fs::File,
    scratch: AlignedBuffer,
    sector: usize,
}

impl WindowsReader {
    fn new(handle: HANDLE, sector: usize) -> Result<Self, AppError> {
        use std::os::windows::io::FromRawHandle;
        let file =
            unsafe { std::fs::File::from_raw_handle(handle.0 as std::os::windows::io::RawHandle) };
        let scratch = AlignedBuffer::new(crate::core::BLOCK_SIZE + sector * 2, sector)
            .ok_or_else(|| AppError::device("cannot allocate aligned read buffer"))?;
        Ok(Self {
            file,
            scratch,
            sector,
        })
    }
}

impl BlockReader for WindowsReader {
    fn read_at(&mut self, offset: u64, buf: &mut [u8]) -> io::Result<()> {
        use std::io::{Read, Seek};
        let aligned_len = buf.len().div_ceil(self.sector) * self.sector;
        let slice = self.scratch.slice_mut();
        if aligned_len > slice.len() {
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                "verify chunk larger than aligned scratch buffer",
            ));
        }

        let attempt = |file: &std::fs::File, len: usize| -> std::io::Result<usize> {
            let mut filled = 0usize;
            file.seek(std::io::SeekFrom::Start(offset))?;
            while filled < len {
                match file.read(&mut slice[filled..len]) {
                    Ok(0) => break,
                    Ok(n) => filled += n,
                    Err(e) if filled > 0 && e.kind() == io::ErrorKind::Interrupted => continue,
                    Err(e) => return Err(e),
                }
            }
            Ok(filled)
        };

        let mut filled = attempt(&self.file, aligned_len);
        if filled.is_err() && aligned_len > self.sector {
            // The padded tail may extend past the end of the medium; retry one
            // sector shorter before giving up. If even that cannot cover the
            // requested bytes, report the error honestly.
            let shorter = aligned_len - self.sector;
            if shorter >= buf.len() {
                filled = attempt(&self.file, shorter);
            }
        }
        let filled = filled?;
        if filled < buf.len() {
            return Err(io::Error::new(
                io::ErrorKind::UnexpectedEof,
                "short read during verification",
            ));
        }
        buf.copy_from_slice(&slice[..buf.len()]);
        Ok(())
    }
}

fn sector_size_of(handle: HANDLE) -> usize {
    let mut geo_buf = [0u8; 24];
    if ioctl(
        handle,
        IOCTL_DISK_GET_DRIVE_GEOMETRY,
        None,
        Some((geo_buf.as_mut_ptr(), geo_buf.len() as u32)),
    )
    .is_ok()
    {
        u32_at(&geo_buf, 20).unwrap_or(512) as usize
    } else {
        512
    }
}

/// Lock + dismount EVERY volume that lives on this PhysicalDrive, so the raw
/// write does not collide with the filesystem driver.
fn lock_and_dismount_volumes(physical: u32, sink: &dyn EventSink) {
    let mask = unsafe { windows::Win32::Storage::FileSystem::GetLogicalDrives() };
    for i in 0..26u32 {
        if mask & (1 << i) == 0 {
            continue;
        }
        let letter = (b'A' + i as u8) as char;
        let Some((number, _)) = volume_device_number(letter) else {
            continue;
        };
        if number != physical {
            continue;
        }
        let path = format!(r"\\.\{letter}:");
        let Ok(handle) = open_path(&path, true, true, false) else {
            continue;
        };
        let locked = ioctl(handle, FSCTL_LOCK_VOLUME, None, None).is_ok();
        let dismounted = ioctl(handle, FSCTL_DISMOUNT_VOLUME, None, None).is_ok();
        let _ = unsafe { CloseHandle(handle) };
        sink.log(format!(
            "windows: volume {letter}: locked={locked} dismounted={dismounted}"
        ));
    }
}

pub fn open_target_pair(
    path: &Path,
    sink: &dyn EventSink,
) -> Result<(Box<dyn BlockWriter>, Box<dyn BlockReader>), AppError> {
    if !is_elevated() {
        return Err(AppError::Permission {
            message: "administrator privileges are required to write raw devices".to_string(),
            hint: Some(
                "Restart AnimaBooter as administrator (the app can do it for you from this \
                 dialog)."
                    .to_string(),
            ),
        });
    }
    let drive_path = path.to_string_lossy().to_string();

    let writer_handle = open_path(&drive_path, true, true, true)?;
    let sector = sector_size_of(writer_handle);

    // PhysicalDrive number from the path itself (\\.\PhysicalDriveN).
    let number: u32 = drive_path
        .rsplit("PhysicalDrive")
        .next()
        .and_then(|s| s.parse().ok())
        .unwrap_or(u32::MAX);
    if number == u32::MAX {
        return Err(AppError::device(format!(
            "unrecognized Windows drive path: {drive_path}"
        )));
    }
    lock_and_dismount_volumes(number, sink);

    let reader_handle = open_path(&drive_path, true, false, true)?;

    Ok((
        Box::new(WindowsWriter::new(writer_handle, sector)?),
        Box::new(WindowsReader::new(reader_handle, sector)?),
    ))
}

pub fn check_flash_allowed(
    drive: &DriveInfo,
    unsafe_mode: bool,
    sink: &dyn EventSink,
) -> Result<(), AppError> {
    crate::safety::assert_flash_allowed(drive, unsafe_mode)?;

    // HARD, NON-OVERRIDABLE: the volume that contains %SystemRoot%.
    let system_root = std::env::var("SystemRoot").unwrap_or_else(|_| "C:\\Windows".to_string());
    if let Some(letter) = system_root.chars().next() {
        if let Some((number, _)) = volume_device_number(letter) {
            if drive
                .path
                .eq_ignore_ascii_case(&format!(r"\\.\PhysicalDrive{number}"))
            {
                return Err(AppError::Safety {
                    message: format!(
                        "{} contains the Windows system volume ({}) — flashing it would destroy the operating system",
                        drive.path, system_root
                    ),
                    hint: Some(
                        "This is a hard safety rule that cannot be overridden, even in unsafe mode."
                            .to_string(),
                    ),
                });
            }
        }
    }
    sink.log(format!(
        "windows: {} is not the system drive — proceeding with lock + dismount on open",
        drive.path
    ));
    Ok(())
}

pub fn eject(path: &Path) -> Result<(), AppError> {
    let drive_path = path.to_string_lossy().to_string();
    let handle = open_path(&drive_path, true, true, false)?;
    let result = ioctl(handle, IOCTL_STORAGE_EJECT_MEDIA, None, None);
    let _ = unsafe { CloseHandle(handle) };
    result.map_err(|e| AppError::Device {
        message: format!("eject failed: {}", e.to_string()),
        hint: Some("Use the 'Safely Remove Hardware' tray icon if the drive is busy.".to_string()),
    })
}
